Controllers/RentingController.cs
using CSCB766_RentACar.Data;
using CSCB766_RentACar.Lib;
using CSCB766_RentACar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSCB766_RentACar.Controllers
{
    
    public class RentingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserService _userService;

        public RentingController(ApplicationDbContext context, IUserService userService)
        {
            _context = context;
            _userService = userService;

        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            //var userId = _userService.GetUserId();
            return View(await _context.RentedVehicles.ToListAsync());
        }

        public async Task<IActionResult> Display()
        {
            return View(await _context.Vehicles.ToListAsync());
        }
        [Authorize]
        public  async Task<IActionResult> RentCar(int? id)
        {
            var userId = _userService.GetUserId();
            var vehicleId = await _context.Vehicles.FindAsync(id);

            if (vehicleId == null)
            {
                return NotFound();
            }
            Rent rent = new Rent()
            {
                UserId = userId,
                VehicleId = vehicleId.VehicleID,
                DateFrom = DateTime.Now,
                DateTo = DateTime.Today.AddDays(1),
                Cost = vehicleId.RentalPricePerDay
            };
            return View(rent);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RentCar(Rent rent)
        {
            if (ModelState.IsValid)
            {
                int vid = rent.VehicleId;
                int from = rent.DateFrom.Day;
                int to = rent.DateTo.Day;
                int totalDays = to - from;
                float price = rent.Cost;
                price *= totalDays;
                rent.Cost = price;
                _context.Add(rent);
                await _context.SaveChangesAsync();

                var vehicle = await _context.Vehicles.FindAsync(vid);
                vehicle.Status = "Unavailable";
                _context.Update(vehicle);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(rent);
           
        }

    }
}

Controllers/VehiclesController.cs
using CSCB766_RentACar.Data;
using CSCB766_RentACar.Lib;
using CSCB766_RentACar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CSCB766_RentACar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        

        public VehiclesController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
           
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vehicles.ToListAsync());
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.VehicleID == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VehicleID,Manufacturer,Model,PlateNumber,RentalPricePerDay,ImageFile,Status")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                //Prepare image for upload then upload to folder wwwroot/uploads
                string rootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(vehicle.ImageFile.FileName);
                string fileExtension = Path.GetExtension(vehicle.ImageFile.FileName);
                vehicle.Image = fileName = fileName + vehicle.VehicleID.ToString() + fileExtension;
                string imagePath = Path.Combine(rootPath + "/Uploads/", fileName);
                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    await vehicle.ImageFile.CopyToAsync(fileStream);
                }

                vehicle.Status = "Available";

                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VehicleID,Manufacturer,Model,PlateNumber,RentalPricePerDay,Image,Status")] Vehicle vehicle)
        {
            if (id != vehicle.VehicleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.VehicleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.VehicleID == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicle = await _context.Vehicles.FindAsync(id);

            // Delete image file from uploads, by first checking if it exists
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "uploads", vehicle.Image);
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            _context.Vehicles.Remove(vehicle);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return _context.Vehicles.Any(e => e.VehicleID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<User> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rent-A-Car</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rent-A-Car</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Renting" asp-action="Display">Browse</a>
                        </li>
                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Renting" asp-action="Index">Details</a>
                            </li>
                        }

                        <partial name="_LoggedInAdmin" />
                    </ul>
                    <partial name="_LoggedInUser" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" >
        <main role="main" class="pb-3" >
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Rent-A-Car - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoggedInAdmin.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<User> _signInManager


@if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
    </li>
}

Views/Shared/_LoggedInUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@inject Microsoft.AspNetCore.Identity.SignInManager<User> _signInManager

<ul class="navbar-nav navbar-right">

    @if (_signInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
        </li>
    }
</ul>